### ISSUE TITLE
Parsing object instance mask

### ISSUE THREAD

**Issue by marioyc** [unrealcv/unrealcv#10]
So, I was the section about the object mask at reading generate-images.ipynb, and I was wondering which is the inefficient part, is it getting the mask or getting the colors?

Also, are the colors going to be constant through time for each object?

**Comment by marioyc** [comment]
If I understood correctly the execution order is (probably with other things in the middle that I wasn't able to follow):

1. FCameraCommandHandler::GetObjectInstanceMask
2. FCommandDispatcher::Exec
3. FPlayerViewMode::Object
4. PaintObjects

and then PaintObjects calls FObjectPainter::Get().PaintRandomColors() which makes it seem like an object wouldn't have the same color across time.

**Comment by qiuwch** [comment]
Yes, the color is constant through time. See [here] (https://github.com/unrealcv/unrealcv/blob/master/Source/UnrealCV/Private/ObjectPainter.cpp#L134). This code is a bit messy and needs to be cleaned up. 

Getting colors for objects only needs to be executed once, so the speed does not matter much. Getting object mask needs to be executed every frame. All the performance bottleneck should be in here.

The execution order and the logic behind is: Every UnrealCV command will be executed by FCommandDispatcher. CommandDispatcher will decide which CommandHandler to use. For `vget /camera/[id]/object_mask`, the FCameraCommandHandler will be used. If this is still unclear, I can point to the specific location in the code. I should write a development page in `unrealcv.github.io` to document this.

PaintObjects happen when the game is initialized. `PaintRandomColors` means iterating over all objects in the scene and assign it a color. If the scene is the same (no object is deleted or added), the color will be the same, no matter running the game how many times. `PaintRandomColors` might not be a very good name.
