### ISSUE TITLE
wrong rgb colorw

### ISSUE THREAD

**Issue by edgarriba** [unrealcv/unrealcv#100]
Hi, I render a view using the following command `vget /camera/0/lit png` throw the python interface. I save in disk the obtained numpy array using opencv and I got the attached image. Is this a bug or am I doing anything wrong ?

![image_ref](https://user-images.githubusercontent.com/5157099/33673656-ad8afede-daad-11e7-99ea-e16373cd69a5.jpg)

**Comment by doublerebel** [comment]
That looks like BGR, not RGB?  Somewhere the channel order has been swapped.

**Comment by oliviersoares** [comment]
@edgarriba OpenCV is using BGR color space.

Convert your numpy array from RGB to BGR before passing it to imwrite:
img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
cv2.imwrite(img_file, img)

(or use cv2.COLOR_RGBA2BGRA if you have an alpha channel)

**Comment by edgarriba** [comment]
@oliviersoares @doublerebel oh right, it worked. Thanks !
