### ISSUE TITLE
Is it possible to run UnrealCV on a model zoo project modification??

### ISSUE THREAD

**Issue by AleBar92** [unrealcv/unrealcv#101]
- Operating System: Windows
- UE4 Version: 4.14.3
- UnrealCV Version: latest
- Client (python2, 3 or matlab):
- Problem Description: I had modified the Realistic Rendering project from UE4 library adding a object. When I packed it, how can i run UnrealCV in it? Hope you can help me. Thanks.

**Comment by zfw1226** [comment]
Hi, you can refer to this [page](http://docs.unrealcv.org/en/latest/plugin/custom_scene.html) to learn how to install UnrealCV in a UE4 project, and [another page](http://docs.unrealcv.org/en/latest/plugin/package.html) to learn how to package a binary equipped with UnrealCV.

**Comment by AleBar92** [comment]
thank you!
