### ISSUE TITLE
"Missing or incompatible modules in UnrealCV plugin" in Windows

### ISSUE THREAD

**Issue by AleBar92** [unrealcv/unrealcv#102]
- Operating System: Windows 10
- UE4 Version: 4.14.3
- UnrealCV Version: latest
- Client (python2, 3 or matlab):
- Problem Description: WhenI try to follow this tutorial here [Install UnrealCV Plugins](http://docs.unrealcv.org/en/latest/plugin/install.html) but it seems not to work. I add, as the tutorial says, a new Folder called Plugins and copy in it the UnrealCV folder downloaded [here](https://github.com/unrealcv/unrealcv/releases) in 0.3.10 version for WIN64. when i try to open my project it show "Missing or Incompatible modules in UnrealCV plugis". What do I do wrong?

**Comment by zfw1226** [comment]
I tested the compiled UnrealCV plugins in UE4.16.3 Windows. It works well. 
Maybe it do not compatible with UE4.14, so you can have a try to compile it from source code. The building script makes it become easy.

**Comment by AleBar92** [comment]
I solve the problem via Source Code, thanks a lot. I have another question although. Where can i find the name of the objects shown by unrealcv plugin to modify them? (e.g. in Realistic Rendering project the big couch name is Couch_13, where can i edit that name??)
(if i have to open another issue just tell me and i'll do it)

**Comment by zfw1226** [comment]
Do you mean that modify the name of the object?

**Comment by AleBar92** [comment]
yes modify the name of an object

**Comment by zfw1226** [comment]
Well, you can edit the name in the UE4 Editor. All of the names are listed in the top right. You can modify the name via double clicking it.

**Comment by AleBar92** [comment]
Ok but they do not correspond with the name seen by UnrealCV Plugin.
Couch15 in Editor == Couch_13 in CVPlugin

**Comment by zfw1226** [comment]
But once you modify the name in UE4 Editor, you can get the same from UnrealCV according to my tests. 
I am not sure the reason that why the original names not matched, maybe it is the feature of Realistic Rendering project.

**Comment by AleBar92** [comment]
Ok, I'll try asap. Thank you so much!

**Comment by qiuwch** [comment]
@zfw1226 @AleBar92. The object name returned from unrealcv is the object id, not the name you see in the editor. 

For example if you hover the mouse on the object, it will show the id. The name you can edit it object label. The label is only available in development build, see [here](https://docs.unrealengine.com/latest/INT/API/Runtime/Engine/GameFramework/AActor/GetActorLabel/index.html). If you check the unreal engine code, you can find the GetActorLabel API is only available for the editor mode, which means the label is not available for a compiled binary.

![image](https://user-images.githubusercontent.com/1688418/33916626-bc458074-df77-11e7-9017-45f873503af5.png)

**Comment by AleBar92** [comment]
Alright. Luckily when i've tried the solution of @zfw1226 it worked well. Thanks a lot for your suggestions!
