### ISSUE TITLE
change port number

### ISSUE THREAD

**Issue by edgarriba** [unrealcv/unrealcv#105]
Hi, is there any way to change to unreal server port number other than modifying by hand the config file ?

**Comment by doublerebel** [comment]
@edgarriba there is an example in [the header of the client python file](https://github.com/unrealcv/unrealcv/blob/master/client/python/unrealcv/__init__.py#L6):
```py
>>> import unrealcv
>>> (HOST, PORT) = ('localhost', 9000)
>>> client = unrealcv.Client((HOST, PORT))
```
The simplest version might be (for example port 9999):
```py
>>> from unrealcv import Client
>>> client = Client('localhost', 9999)
```

**Comment by edgarriba** [comment]
@doublerebel thanks, but I meant the unreal engine server port. I have the use case with more than one binaries running at the same time in the same machine. By default, the binaries use the port 9000.

**Comment by doublerebel** [comment]
The binary port can be set in the config file, `unrealcv.ini`.  There is an example in #83 and the possible values are shown in [UnrealCV/Private/ServerConfig.cpp](https://github.com/unrealcv/unrealcv/blob/6295c4a2ab195175a7508056c8372189041e158f/Source/UnrealCV/Private/ServerConfig.cpp).

**Comment by qiuwch** [comment]
Hi, @edgarriba 

I agree with @doublerebel 

Unrealcv did not have a command to change the server port yet. Currently as a workaround, you might be able to use an ini config parser, such as this https://docs.python.org/2/library/configparser.html to modify the ini config programmatically.

**Comment by edgarriba** [comment]
@doublerebel @qiuwch thanks for your answers ! As a features request, would be nice to have an argument in the binary with the port number and potentially others parameters.
