### ISSUE TITLE
Add domain randomisation implementation

### ISSUE THREAD

**Issue by xd009642** [unrealcv/unrealcv#106]
This is an enhancement but one of the relevantly recent reinforcement learning advancements is domain randomisation to prevent over-fitting. I was considering forking and implementing https://arxiv.org/abs/1703.06907 for my own ML/CV projects. Are there any current plans for similar functionality? Or any preferences in how something like this would be integrated? I was thinking a new command `vget/camera/N/random`

**Comment by qiuwch** [comment]
Thanks for pointing it out. I suggest using blueprint to randomize the materials you want to change. You can easily put what you want to randomize in the Tick function. It can be color, texture, object location, etc.

**Comment by xd009642** [comment]
I'll look at a blueprints solution. Ideally you'd have to manually retrigger the randomisation just to enable longer consistent runs of training data.

**Comment by qiuwch** [comment]
Yes, I agree. We have a command to trigger/call a blueprint function through unrealcv. This command is not well documented now.
