### ISSUE TITLE
changing resolution

### ISSUE THREAD

**Issue by tebishop** [unrealcv/unrealcv#11]
I found after searching online that it's possible to change the resolution of the environment by using the 'setres WxH' command in the game console.

This works for display on screen, but when using the generate-images code, the results are still at 640x480, apart from the object mask, which is at the desired resolution. How would the render size (and perhaps other render settings) be passed on correctly for export to disk?

**Comment by qiuwch** [comment]
It is currently hard-coded [here](https://github.com/unrealcv/unrealcv/blob/master/Source/UnrealCV/Private/GTCaptureComponent.cpp#L19). 
I will make this configurable in the next release (in a few days). I am working on setting up the Jenkins CI system.

**Comment by mikeroberts3000** [comment]
Hi @tebishop, in case it's helpful, I have successfully changed the resolution of the UnrealCV screenshots by editing the ``unrealcv.ini`` file, which for me is located at ``/Users/Shared/EpicGames/UE_4.14/Engine/Binaries/Mac/unrealcv.ini``. This functionality was added relatively recently, so you should update to the latest version of UnrealCV.

**Comment by abhay-venkatesh** [comment]
I cannot find my config file. My "vget /unrealcv/status" only returns "Is Listening
Client Connected
9000"

**Comment by Eddie-91** [comment]
we changed unrealcv.ini to
[UnrealCV.Core]
Port=9000
Width=1920
Height=1440
FOV=90.000000
EnableInput=True
EnableRightEye=False

but after running "res = client.request('vget /unrealcv/status')", mwe still get:
INFO:__init__:192:Got connection confirm: b'connected to fly'
Is Listening
Client Connected
9000
Configuration
Config file: D:/qile/svn/unrealcv/UE4Binaries/fly/WindowsNoEditor/fly/Binaries/Win64/unrealcv.ini
Port: 9000
Width: 640
Height: 480
FOV: 90.000000
EnableInput: true
EnableRightEye: false

Width and Height are not changed

**Comment by epicman22** [comment]
How to change the resolution of screenshot with unrealcv?

**Comment by zfw1226** [comment]
@epicman22 [Here](https://github.com/zfw1226/gym-unrealcv/blob/v1.0/gym_unrealcv/envs/utils/env_unreal.py#L94-L104) is an example of writing the unrealcv.ini file to change the resoluation before launching the unrealcv binary.
