### ISSUE TITLE
Generating 16 megapixel images with UnrealCV

### ISSUE THREAD

**Issue by larjung** [unrealcv/unrealcv#110]
- Operating System: Ubuntu 14.04.5 LTS
- UE4 Version: 4.16.3
- UnrealCV Version: 0.3.10
- Client (python2, 3 or matlab): 2.7.13
- Problem Description:

Hi, I’m trying to generate a couple of lit and depth images at 16 megapixel resolutions such as 4920 x 3264 using UnrealCV 0.3.10 and Unreal Editor 4.16.3 for Linux.

Unfortunately, the vget client requests fail with a timeout because the operation takes longer than 5 seconds. I have tried to pass a longer timeout parameter through request() but UnrealCV still times out before it can finish.

Smaller resolution images at 4k definition and lower do work properly. The issue starts once I try to get higher resolution images that take longer to process.

Is there a way to increase the timeout when generating high resolution lit and depth images to allow this operation to succeed?

**Comment by qiuwch** [comment]
Hi @larjung 

Sorry for late reply. If you search timeout in the code, you can find a few places with timeout threshold.

The 5 seconds timeout is defined in https://github.com/unrealcv/unrealcv/blob/24ba34eab164cff07832f4e0a7d44b578f42b7c8/Source/UnrealCV/Private/CommandDispatcher.cpp#L71.

**Comment by larjung** [comment]
Hi @qiuwch 

The code change worked as described and I can now generate 16MPixel images with UnrealCV.

Thanks!

**Comment by qiuwch** [comment]
@larjung  Cool. Glad to know that. Let me know if you need any other help.
