### ISSUE TITLE
MIssing file camera_traj.json

### ISSUE THREAD

**Issue by krydm** [unrealcv/unrealcv#120]
- Operating System:Mac High Sierra 10.13.3
- UE4 Version:4.16, patch 3
- UnrealCV Version: 0.3.10
- Client (python2, 3 or matlab): Python2, Python3
- Problem Description: Just getting started with unrealcv. I've opened python(the picture is the same with both 2 and 3) and connect the client(running RealisticRendering, just in case it matters). The client is connected OK, and I can run  res = client.request('vget /unrealcv/status').
However, when I'm trying to call json.load(open('./camera–traj.json')) -- I get
IOError: [Errno 2] No such file or directory './camera–traj.json'
Same happens with file object_category.json.
I've ran search from Mac's Finder and it indeed doesn't find these files.
What's wrong with my unrealcv install? TIA

**Comment by SteveJos** [comment]
Hey it is located in `unrealcv/docs/tutorials:)`

**Comment by krydm** [comment]
@SteveJos don't laugh, but I still don't get it. I'm following Gettin Started. After pip install unrealcv I've only found unrealcv folder in Python packages, and it's definitely not there. OK, looking at your answer I've realized that it was my stupidity and I should clone the repo first. The cloned repo does have a docs subfolder, but no tutorials. I run python build_doc.py(not even sure if it's going to help, but why not) there and it doesn't go complaining about missing module sphinx_issues. Is there any step-by-step guide for setup? TIA ;)

**Comment by krydm** [comment]
My fault, I've checked the git logs -- there was 
git-lfs smudge 'docs/images/console.png': git-lfs: command not found
in the middle of cloning. Installed git-lfs and now I see the tutorials folder with all the contents including json files.
I apologize for the mess
