### ISSUE TITLE
Please provide the "rr_573.json" file for `data_generation.py` sample code

### ISSUE THREAD

**Issue by SteveJos** [unrealcv/unrealcv#121]
- Operating System: Ubuntu 16.04
- UE4 Version: 4.17 
- UnrealCV Version: Master
- Client (python2, 3 or matlab): Pyhton 2.7
- Problem Description:

@TaeSoo-Kim @qiuwch 
Please provide the `rr_573.json` file that is used in the `data_generation.py` sample code. How should the 'scene_name' and 'cam_info' entrys look like?

Thank you very much in advance!

**Comment by qiuwch** [comment]
See whether this can work? It is written for an earlier version, so it might be need small modification, https://gist.github.com/qiuwch/90067ca6ef3e80642c47f190d8b13159

**Comment by SteveJos** [comment]
Thank you very much! Yes the json worked but the format is quite different from the one generated in `camera_traj.json`. Therefore camera trajectories generated with `record_camera_trajectory.py` are not compatible.
