### ISSUE TITLE
unrealcv/examples/10lines.py problem

### ISSUE THREAD

**Issue by krydm** [unrealcv/unrealcv#122]
- Operating System:
- UE4 Version:
- UnrealCV Version:
- Client (python2, 3 or matlab):
- Problem Description:
I'm trying to run 10lines.py with RealisticRendering(doesn't matter, I guess) and I get an error:
File "/Users/dmitri/unrealcv_tutorials/camera_traj.py", line 15, in <module>
    [im, dep, obj] = [client.request('vget /camera/0/%s' % m) for m in modes]
ValueError: need more than 2 values to unpack
(or, with Python3 it is 'not enough values to unpack (expected 3, got 2)' -- obviously the same)

I've checked the request result, and there's indeed just two elements, something like:

[u'/private/var/folders/vf/d8f6xsh11ddfh7tgw3lfpjfm0000gn/T/AppTranslocation/9F775AC2-7155-4F94-8871-986BE75CC4C1/d/RealisticRendering.app/Contents/UE4/Engine/Binaries/Mac/00000003.png', u'/private/var/folders/vf/d8f6xsh11ddfh7tgw3lfpjfm0000gn/T/AppTranslocation/9F775AC2-7155-4F94-8871-986BE75CC4C1/d/RealisticRendering.app/Contents/UE4/Engine/Binaries/Mac/00000004.png']

Could somebody advise please? TIA

**Comment by SteveJos** [comment]
Hey @krydm! There is a depth param missing in the example.. just replace the line 14 (modes) with the following:

`modes = ['lit', 'object_mask', 'depth']`

**Comment by krydm** [comment]
@SteveJos many thanks! It's actually a shame that I didn't care to read the code thoroughly. Just ten clear lines :(. 
OK, I'm a rather freshman in Python
