### ISSUE TITLE
client connection/disconnection

### ISSUE THREAD

**Issue by krydm** [unrealcv/unrealcv#127]
- Operating System:Mac High Sierra 10.13.3
- UE4 Version: 4.16
- UnrealCV Version: 0.3.10
- Client (python2, 3):
- Problem Description:
I'm running some code starting with 
client.connect()
 and ending with client.disconnect()

Despite this disconnect code attempt to rerun this code again causes the following traces repeatedly:
ERROR:__init__:336:Can not receive a response from server, timeout after 5.00 seconds
ERROR:__init__:230:Fail to send message, client is not connected

The only way to rerun is to stop UE4 and restart it.
Is it just my wrong API usage?I couldn't find any examples which use, say, connection id for disconnect. Please advise.
TIA

**Comment by dimka-kopitkov** [comment]
Up. I've experienced similar problems with connection socket. I'm connecting to plugin from Matlab and on some occasions plugin stops responding and the only way to deal with it is to restart UE4.
I didn't yet investigate what exactly caused the connection to get broken.

**Comment by krydm** [comment]
@dimka-kopitkov wow, so with the plugin it happens just occasionally? Python client gives it 10 out of 10 ;)

**Comment by qiuwch** [comment]
If my memory is right, the mac socket did not detect the disconnection the same way as windows / Linux. This is a known bug and I don't have enough energy to fix it on Mac. Sorry.

**Comment by krydm** [comment]
@qiuwch gotcha, thanks. Maybe as a half–solution you could return the socket on connect()? Then we could at least take care of it out of the client.

**Comment by krydm** [comment]
@qiuwch I see. Completely agree about the platform-related part, and our stuff at the end will be deployed to Linux and run there, but we're now at the very first part of research/prototyping, so it's mainly playing/trying/checking etc. So the issue is just a bit annoying but not very critical. Many thanks for the clarification though.
Could you maybe also comment on the issues #126 and #117 please? They look more sufficient. TIA

**Comment by qiuwch** [comment]
@krydm Sure. Will do.
