### ISSUE TITLE
Compiling the plugin error

### ISSUE THREAD

**Issue by dineshreddy91** [unrealcv/unrealcv#13]
Currently i am trying to compile the unrealCV plugin into Unreal engine 4.12. I get this error during make

UnrealEngine/Engine/Plugins/unrealcv/Source/UnrealCV/Public/TcpServer.h(50): Error: Property is exposed to the editor or blueprints but has no Category specified.

Property is exposed to the editor or blueprints but has no Category specified.

which version of unreal engine are you working with??

**Comment by mikehaney24** [comment]
you should look at the issues before posting a new one

https://github.com/unrealcv/unrealcv/issues/12

**Comment by qiuwch** [comment]
@dineshreddy91 Please have a look at #12

**Comment by qiuwch** [comment]
Code is updated in #21
