### ISSUE TITLE
Landscapes not visible in object mask view

### ISSUE THREAD

**Issue by CallumFling** [unrealcv/unrealcv#135]
- Operating System: Win 7
- UE4 Version: 4.16
- UnrealCV Version: lastest fast branch
- Client (python2, 3 or matlab): python2
- Problem Description:
When using the object mask view mode, mask colours aren't painted onto landscape objects. Standard meshes work fine.

The issue echoes that seen in #17 but the supplied fix to that issue doesn't solve the problem and the landscape, instance grass etc. still doesn't show up in mask view mode.

Any assistance is greatly appreciated.

**Comment by CallumFling** [comment]
After more digging into this issue, using a slightly modified fast branch build on Unreal 4.17 leads to the landscape being visible in the world, but not painted any colours.

Using the master branch of unreal CV leads to the same result, a visible yet grey landscape that cannot have its colour changed. @qiuwch do you have any idea what may be causing this?

I have also tried a build of both unreal engine and the unrealCV plugin on a linux machine (Ubuntu 16.04) and meet the same results with 4.16 of the landscape being invisible in object_mask mode.

Thanks,

**Comment by JimmyLaessig** [comment]
I'm closely working with the plugin for a research project:
I can pretty safely say that with the current setup, landscapes won't be visible on the object mask. The reason for this is that UnrealCV stores the object mask id in an per-instance overideable vertex color buffer. Unfortuantely, they only consider static meshes for now, so the color buffer will no tbe overriden for every other mesh type (i.e. ALandscape meshes). This behaviour bugs me as well, but I haven't found a workaround so far... Other approaches use the custom stencil buffer to render a class label to the screen, but this approach is limited to 2^8 values.

**Comment by CallumFling** [comment]
I figured that was the case and this method was limited only to static meshes for the moment. A quick and dirty work around I have been using has been to use a series of smaller static meshes for terrain and just accept the fact i will be using a smaller world size and losing out on the LOD benifits the landscape brings to the table. That and the nice UE terrain painting/generation methods that exist.

Hopefully this is something that can be added in future or have a system similar to the stencil approach as for many use cases, <=255 classes probably wont be an issue.

**Comment by Ahleroy** [comment]
Using UnrealCV 3.10 with UE4.16.3 the landscape is displayed as a gray surface but with the lightning applied on it.  Th surface is not a perfect grey (blue = red = green). Therefore a post processing task could involve a k-mean if the number of class is not too big.

```python 

K = 2 # Number of classes expected

import numpy as np
import cv2

img = cv2.imread('object_mask.png')
Z = img.reshape((-1,3))

# convert to np.float32
Z = np.float32(Z)

# define criteria, number of clusters(K) and apply kmeans()
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)

ret,label,center=cv2.kmeans(Z,K,None,criteria,10,cv2.KMEANS_RANDOM_CENTERS)

# Now convert back into uint8, and make original image
center = np.uint8(center)
res = center[label.flatten()]
res2 = res.reshape((img.shape))

cv2.imwrite("result.png", res2)```

**Comment by CallumFling** [comment]
As a quick update to this (sorry it has been so long 😞 ) but by placing a bunch of engine showFlags function calls in the object annotation code.

This leads to landscapes being visible and not shaded with a locked value of 76 (I think, can check in the new year if anyone really wants me to) which is perfectly usable for my use case and hopefully others too.

If anyone wants, I can drop the exact showFlags commands I have placed and where have put them in a week or so.

This seems to be an appropriate work around to this as the object painter system implementation here just isn't compatible with the crazy UE4 landscape system (Not a gripe against this project, this project is amazing! 😃 )

I will close this issue in the new year after this comment has sat here for a bit...

**Comment by olgkad2** [comment]
@CallumFling, hi! I know it's been a long time, but do you by any chance remember the exact commands that you used? It would be of great help!

**Comment by CallumFling** [comment]
Hi @olgkad2, sorry for the late reply!

In order to get the landscapes showing up, I modified the `AnnotationCamSensor.cpp` file by adding the line `this->PrimitiveRenderMode = ESceneCapturePrimitiveRenderMode::PRM_RenderScenePrimitives;` within the constructor.

The caveat with this method is, while landscapes now show up, they show up locked as a mask value of 76 (this seems to be some sort of default value) and cannot be changed sadly. For my use case, this is OK as i just later replace these colours as desired in Python.

Definitely not a great solution to the problem I do admit, but as a workaround I found it worked well for me in my use case.

Hope it helps!

**Comment by olgkad2** [comment]
@CallumFling  Thanks a lot! Any solution will do it for me haha

**Comment by CallumFling** [comment]
@olgkad2 I should also mention that as a solution to the issue noticed by @Ahleroy, you can extend the ShowFlags in the AnnotationcamSensor constructor to include disabling lighting related options found in this doc page (https://api.unrealengine.com/INT/API/Runtime/Engine/FEngineShowFlags/index.html) 

I disabled everything to do with lighting in the constructor and CaptureSeg functions of the `AnnotationCamSensor.cpp` file and the landscapes showed up as a perfect uniform gray value of 76. Use the format for setting these already present in the constructor and ensure all lighting options are false.

Hopefully this helps if you run into this issue too!
