### ISSUE TITLE
Load unrealcv plugin failed

### ISSUE THREAD

**Issue by wymdhr** [unrealcv/unrealcv#16]
I download the zip on your tutorial page https://unrealcv.github.io/tutorial/plugin.html, and copied to the Plugins folder of Unreal Engine (Engine/Plugins). 
 And the error is I can't open the unreal because failed to load the UnrealCV  module.
 I try to put it in my project and failed, either. tip is missing or incompatible modules in UnrealCV plugin
Thanks for your help～

**Comment by wymdhr** [comment]
OK，，I find issue #12，and it worked fine, but is there any way that don't need to recompile unreal?

**Comment by qiuwch** [comment]
I conjecture you are using a Mac, is it right?
I did not contain a compiled mac version in the zip file yet, but this will be solved, because #15 #7 .

**Comment by qiuwch** [comment]
@wymdhr  Is your problem the same as #25?

**Comment by wymdhr** [comment]
Yes, we got the error information. Maybe there miss some files in the plugin folder, so follow issue #12, modify one line in source code, recompile the unreal may solve this error.
