### ISSUE TITLE
UnrealCV module cannot be found in UE 4.22

### ISSUE THREAD

**Issue by medhagitnod** [unrealcv/unrealcv#166]
- Operating System: Ubuntu 18.04
- UE4 Version: 4.22
- UnrealCV Version: v. 0.3.10
- Client (python2, 3 or matlab): python 2
- Problem Description: When following the installation tutorial in the documentation, I have moved the UnrealCV folder into the Unreal Engine plugin folder. When attempting to launch Unreal Engine I get this message: 'Plugin 'UnrealCV' failed to load because module 'UnrealCV' module cannot be found. Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project'. The plugin is very clearly in the plugins folder, so what could be the issue?

**Comment by ChrisGoKim** [comment]
Hey medhagitnod. I've been having this same issue in UE4 Version 4.18. I can't figure out what's wrong although this is an incredibly basic installation set-up. How did you resolve this issue? Thanks.

**Comment by flashal1** [comment]
how did you slove it ,thanks
