### ISSUE TITLE
Objects other than StaticMeshActors do not show up in modes other than lit

### ISSUE THREAD

**Issue by kenryd** [unrealcv/unrealcv#17]
I'm relatively new at using Unreal Engine. I've created a simple map with a StaticMeshActor floor as well as a Landscape object using the UE4Editor. When I hit "Play" in the editor, the entire scene is visible. However, when I switch viewmodes to depth (or normal, or object_mask), then the non-static-mesh objects are no longer visible. I've found that this occurs with other objects as well. If I export the Landscape as an object and then re-import it as a static mesh, then it is visible, but this workaround would not scale to a large map with many objects.

**Comment by qiuwch** [comment]
I fixed the issue in #22. It is a mistake I made when changing the rendering setting.
