### ISSUE TITLE
Custom image resolution not working

### ISSUE THREAD

**Issue by Jorge-IAV** [unrealcv/unrealcv#182]
- Operating System: Linux
- UE4 Version: 4.21
- UnrealCV Version: latest fast branch
- Client (python2, 3 or matlab): python2
- Problem Description: I am trying to get images with the object mask at a resolution of 1280x720. However, the images I get are always 640x480. I have tried modifying the unrealcv.ini file but it doesn't seem to work. The file looks like this: 

> [UnrealCV.Core]
> Port=9000
> Width=1280
> Height=720
> FOV=90.000000
> EnableInput=True
> EnableRightEye=False

I ran the client.request('vget /unrealcv/status') command and I get: 

> The last update of this file: 2020-02-07 09:32:18
> INFO:__init__:192:Got connection confirm: 'connected to Project6_Farm'
> Is Listening
> Client Connected
> 9000
> Configuration
> Config file: /hdd/UnrealEngine-4.21/Engine/Binaries/Linux/unrealcv.ini
> Port: 9000
> Width: 640
> Height: 480
> FOV: 90.000000
> EnableInput: true
> EnableRightEye: false

My plugin version is 0.3.10, any Idea why it is not working?

**Comment by epicman22** [comment]
Hi,
Any solution for this?
