### ISSUE TITLE
ERROR:__init__:205:Can not connect to ('localhost', 9000)

### ISSUE THREAD

**Issue by xi-mao** [unrealcv/unrealcv#193]
- Operating System: Ubuntun18
- UE4 Version:       4.19
- UnrealCV Version:    1.0
- Client (python2, 3 or matlab):   python3，
- Problem Description: my unrealcv suddenly can't connect to the environment from yesterday. like this:
>>> from  unrealcv import client
>>> client.connect()
ERROR:__init__:205:Can not connect to ('localhost', 9000)
ERROR:__init__:206:Error [Errno 111] Connection refused

before，i can connect successfully, but now it failed

**Comment by xi-mao** [comment]
@zfw1226   thanks, i have fixed it

**Comment by jlcd** [comment]
This may help someone, but running Windows with an Ubuntu on WSL2, as always got `connection refused` from `localhost` or `127.0.0.1`.

So what helped me was [this](https://github.com/microsoft/WSL/issues/384#issuecomment-676827920) comment on an WSL2 issue regarding not being able to access the Windows host `localhost` from the WSL2 container.

After running those commands and enabling `avahi`, now I'm able to access the UnrealCV server using a `.local` hostname.
