### ISSUE TITLE
How to obtain the camera's parameters

### ISSUE THREAD

**Issue by ThompsonHe** [unrealcv/unrealcv#197]
- Operating System:
- UE4 Version:
- UnrealCV Version:
- Client (python2, 3 or matlab):
- Problem Description:
We recently are going to use unrealcv to do some cv research. But we found not api to get the camera's intrinsic parameters.Could you please tell me about the way to do that?Thanks for your help!

**Comment by qiuwch** [comment]
Hi, @ThompsonHen 

If you did not change the camera FOV, the default FOV is 90 and you can compute the intrinsic parameter from it.

A discussion can be found in issue #14

**Comment by ThompsonHen** [comment]
> Hi, @ThompsonHen
> 
> If you did not change the camera FOV, the default FOV is 90 and you can compute the intrinsic parameter from it.
> 
> A discussion can be found in issue #14
@qiuwch 
Appreciate your reply
