### ISSUE TITLE
Object mask

### ISSUE THREAD

**Issue by Noelok** [unrealcv/unrealcv#20]
Hi Weichao,

Awesome work!! I'm new to Unreal, I would like to use unrealCV for a deep learning project. I have issues to assign a color ID to objects. After I packaged my unreal (4.12) project, I can't access to the command line. The only way to connect to the package is through a command console. Then I can switch from depth to normal to lit. Using the "vset /object/[object_name]/color 255 0 0" command doesn't work. It returns this error : "IndentationError: unexpected indent".
My goal is to create a script that will randomly assign color ID to all the objects in my scene. 
(I tried to connect to the unreal editor with my scene loaded and I have this error "can not connect to ('localhost', 9000) | Error [Errno 10061] No connection could be made because the target machine actively refused it")
Did I miss something? Any help will be much appreciated :)
Thank you!
Noel.

**Comment by Noelok** [comment]
Hello,
Am I the only one with this issue?

**Comment by qiuwch** [comment]
"IndentationError: unexpected indent". This sounds like a python error. Where did you see this error? Can you paste more detailed error message?

For the `can not connect to` error, there might be several reasons. The most common issue is port 9000 is in use. Can you run `vget /unrealcv/status` and see what it returns?

**Comment by Noelok** [comment]
Hi Weichao,
Thank you for your reply. 
Here is a screenshot of the error msg I've got when I tried to connect to my unreal scene with unreal launched from a command shell.
![capture](https://cloud.githubusercontent.com/assets/22223962/19049550/c72b0780-895f-11e6-8837-377005515353.JPG)

The UnrealCV plugin is installed : 
![capture2](https://cloud.githubusercontent.com/assets/22223962/19049634/177c1b8e-8960-11e6-844a-c5f97c005538.JPG)

Because I couldn't connect, I exported my scene as a package for windows 64bits. I launched the package and I was able to connect using a command shell. When I run the command "vget /unrealcv/status" I got this: "Is listening\nClient Connected\9000\n"
![capture3](https://cloud.githubusercontent.com/assets/22223962/19049971/6c2cc236-8961-11e6-829d-3afdcde38ada.JPG)

The "IndentationError: unexpected indent" message is when I run this command from a command shell: 
"vset /object/[object_name]/color 255 0 0" . I'd like to set an ID color to my object

Thank you for your help,
Noel.

**Comment by qiuwch** [comment]
For the first question: when you are not able to connect to the editor using python script, you can still type command in the console of UE4 Editor. It will be something looks like this, I want to see the status in the editor.

![screenshot from 2016-10-03 18 44 27](https://cloud.githubusercontent.com/assets/1688418/19056801/6fab09f8-8999-11e6-8e02-f1f938b63518.png)

**Comment by oliviersoares** [comment]
Hi @qiuwch, thanks for this plugin.

I have a very similar issue. I compiled everything from source for UE 4.13.
I created a package from the Realistic Rendering UE4 scene in the marketplace.

When starting the standalone scene, then trying to connect the client from python, it's failing to connected (see screenshot below).

<img width="1323" alt="screenshot" src="https://cloud.githubusercontent.com/assets/4942869/19167951/bb8fb410-8bc2-11e6-816d-2388de968540.png">

Note that the same thing is working if I use the version of Realistic Rendering downloaded from your website or if I build the package in UE 4.12 with your plugin.

But using the version compiled from latest github with UE 4.13, no luck...

Thanks!
-olivier

**Comment by qiuwch** [comment]
Hi @oliviersoares:

I did not do a lot of testing with 4.13 yet. This is weird, let me do some diagnosis and get back to you tomorrow.

**Comment by oliviersoares** [comment]
Thanks @qiuwch, much appreciated.

I did a test with 4.12, compiled from the same source (latest github) and I could make everything work nicely. So it seems to be an issue with 4.13.

Note that I still have the same issue Noel described which is when playing the scene directly from Unreal, the client won't connect. However it will connect properly when building a standalone package.

As a side note, for 4.13 to work, I had to change this line from an Error to a Warning:
https://github.com/unrealcv/unrealcv/blob/master/Source/UnrealCV/Private/TcpServer.cpp#L267

Without this change, Unreal generates an error when building the package and fails (might be related to the underlying issue with 4.13).

Thanks again,
-olivier

**Comment by Noelok** [comment]
Hi Weichao,
Sorry for my late reply. 
So in 4.12, when I run the command "vget /unrealcv/status"
I got this : 
![capture](https://cloud.githubusercontent.com/assets/22223962/19175456/9d5b8798-8beb-11e6-9ea3-7d928b09f7a7.JPG)

**Comment by qiuwch** [comment]
Hi, @Noelok @oliviersoares:

Sorry for getting back to you after such a long delay.
The compatible issue should be fixed in the v0.3.0, if you are still interested in using this tool, please give it a try. Thanks.

**Comment by Noelok** [comment]
Hi Weichao,
Thanks for the update! We are really interested in using this tool! :)
I'm testing it in 4.13
Thanks!

**Comment by qiuwch** [comment]
Thanks for feedback and let me know if you find any issue.  : )
