### ISSUE TITLE
help on ue4 theory, how unrealcv works?

### ISSUE THREAD

**Issue by HaiyiMei** [unrealcv/unrealcv#201]
I'm curious about how unrealcv plugin set actors in the scene to pure color when generating object_mask, i.e. how unrealcv works. Can you give me some clues about it? Really appreciate it. Thanks!

**Comment by zfw1226** [comment]
This command would be helpful for you:
`vset /object/[obj_name]/color [r] [g] [b]`
Set the labeling color of an object

**Comment by HaiyiMei** [comment]
> This command would be helpful for you:
> `vset /object/[obj_name]/color [r] [g] [b]`
> Set the labeling color of an object

Thx for the quick reply. Sorry I didn’t describe properly. I want to know what does this command do to make actors change to pure color, i.e. how can I do it through C++ or blueprint in ue4 without unrealcv.

**Comment by HaiyiMei** [comment]
TimmHess/UnrealImageCapture#3 This is a great tutorial I found. Hoping this can help confused guys like me.
