### ISSUE TITLE
Clarify Eurler Angles in the Documentation

### ISSUE THREAD

**Issue by Maltergate** [unrealcv/unrealcv#207]
Documentation is far from clear when it comes to the use of the rotation. What is the type of Euler Angles that are used ? What's the order of application of the angles ? Is it a local or a global rotation ? The fact that the ordering is "pitch yaw roll" is a bit unsettling because neither the aerodynamic groups nor the roboticists use this convention.

Please update the documentation.

Even better : enable quaternion support (and detail convention used).

Thanks

**Comment by leobobsix** [comment]
I have the same question. Given the same [pitch, yaw, roll] to UnrealCV and UE4 panel, they came to different rotations. So weird.
