### ISSUE TITLE
Build failed for UE4.26

### ISSUE THREAD

**Issue by gaoyuanzizizi** [unrealcv/unrealcv#216]
- Operating System: Windows
- UE4 Version: 4.26
- UnrealCV Version: 3.0.10
- Client (python2, 3 or matlab): python3
- Problem Description: 
I have tried to build UnrealCV for UE4.26 but it has failed.Can you please inform whether there is any support for this or not?

$ python build.py --UE4 "E:\Program Files\Epic Games\UE_4.25"
Running AutomationTool...
Parsing command line: BuildPlugin -plugin=E:\PythonDocuments\unrealcv-0.3.10\UnrealCV.uplugin -package=E:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV -rocket -targetplatforms=Win64
Copying 138 file(s) using max 64 thread(s)
Reading plugin from E:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\UnrealCV.uplugin...
Building plugin for host platforms: Win64
Running: E:\Program Files\Epic Games\UE_4.25\Engine\Binaries\DotNET\UnrealBuildTool.exe UE4Editor Win64 Development -Project=E:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV\HostProject\HostProject.uproject -plugin=E:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\UnrealCV.uplugin -iwyu -noubtmakefiles -manifest=E:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV\HostProject\Saved\Manifest-UE4Editor-Win64-Development.xml -nohotreload -log="C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\E+Program+Files+Epic+Games+UE_4.25\UBT-UE4Editor-Win64-Development.txt"
  While compiling E:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV\HostProject\Intermediate\Build\BuildRules\HostProjectModuleRules.dll:
  e:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\Source\UnrealCV\UnrealCV.Build.cs(18,41) : error CS0122: “UnrealBuildTool.BuildConfiguration”不可访问，因为它受保护级别限制
  e:\PythonDocuments\unrealcv-0.3.10\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\Source\UnrealCV\UnrealCV.Build.cs(51,8) : error CS0103: 当前上下文中不存在名称“UEBuildConfiguration”
  ERROR: Unable to compile source files.
Took 3.439s to run UnrealBuildTool.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\E+Program+Files+Epic+Games+UE_4.25\UBT-UE4Editor-Win64-Development.txt)
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED

**Comment by Wang-Minxin** [comment]
Hi, I have the same problem, could you tell me how to solve it? Thank you very much!
