### ISSUE TITLE
Build failed for UE4.27

### ISSUE THREAD

**Issue by ramparvathaneni** [unrealcv/unrealcv#220]
- Operating System: Windows 10
- UE4 Version:4.27
- UnrealCV Version: cloned from branch 4.27 seems like v0.3.10
- Client (python2, 3 or matlab): 3.10
- Problem Description: Build Failed Exited with code 6
- 
[Log.txt](https://github.com/unrealcv/unrealcv/files/7915476/Log.txt)
[UBT-UE4Editor-Win64-Development.txt](https://github.com/unrealcv/unrealcv/files/7915477/UBT-UE4Editor-Win64-Development.txt)

**Comment by TodaYuto** [comment]
I can't build due to the same error

**Comment by Ericgeese** [comment]
My temporary solution to fix build error in branch 4.27:
1. **Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.**
Solution: Find all the **UPROPERTY()** at locations of error and add a **Category** domain. e.g. **UPROPERTY(XXX, Category = "unrealcv")**
2. **Error: use of undeclared identifier 'ECameraProjectionMode'**. 
Solution: Follow [#195 ](https://github.com/unrealcv/unrealcv/issues/195)
3. **Error: declaration shadow**.
Solution: Change enum **Error** to **$Anything** in line 34, **Public/Server/ExecStatus.h** and modify corresponding enums in **Private/Server/ExecStatus.cpp**

By the way, I hope my temporary solution doesn't cause any potential runtime malfunction. @qiuwch

**Comment by chijie1998** [comment]
> My temporary solution to fix build error in branch 4.27:
> 
> 1. **Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.**
>    Solution: Find all the **UPROPERTY()** at locations of error and add a **Category** domain. e.g. **UPROPERTY(XXX, Category = "unrealcv")**
> 2. **Error: use of undeclared identifier 'ECameraProjectionMode'**.
>    Solution: Follow [#195 ](https://github.com/unrealcv/unrealcv/issues/195)
> 3. **Error: declaration shadow**.
>    Solution: Change enum **Error** to **$Anything** in line 34, **Public/Server/ExecStatus.h** and modify corresponding enums in **Private/Server/ExecStatus.cpp**
> 
> By the way, I hope my temporary solution doesn't cause any potential runtime malfunction. @qiuwch

Thanks, able to build and run in windows for UE4.27. So far have no issue to use unrealcv command during play mode.

**Comment by pipi-hua** [comment]
Hi, Referring to the following pages[....]( https://www.unrealengine.com/marketplace/zh-CN/product/enhanced-vehicle-plugin/questions?sessionInvalidated=true)，I tried to change those lines in the .h file where the error was reported.
Like in:
`\Source\UnrealCV\Public\Sensor\CameraSensor\DepthCamSensor.h` line 20 `UPROPERTY(EditInstanceOnly)`
to `UPROPERTY(EditInstanceOnly, Category = BlueprintReadWrite)`.
And treat the other lines that report errors in the same way.
I don't know much about the UE4 functions, but I just did it first and it worked. Maybe it will lead to more unexpected bugs.
Hope it works for you, and if you figure out why it works, please let me know, thanks.

**Comment by pipi-hua** [comment]
> I can't build due to the same error

Please refer to the response above.

**Comment by pipi-hua** [comment]
> * Operating System: Windows 10
> * UE4 Version:4.27
> * UnrealCV Version: cloned from branch 4.27 seems like v0.3.10
> * Client (python2, 3 or matlab): 3.10
> * Problem Description: Build Failed Exited with code 6
> 
> [Log.txt](https://github.com/unrealcv/unrealcv/files/7915476/Log.txt) [UBT-UE4Editor-Win64-Development.txt](https://github.com/unrealcv/unrealcv/files/7915477/UBT-UE4Editor-Win64-Development.txt)

Please refer to the response above.

**Comment by wangxiangsheng123** [comment]
> * Operating System: Windows 10
> * UE4 Version:4.27
> * UnrealCV Version: cloned from branch 4.27 seems like v0.3.10
> * Client (python2, 3 or matlab): 3.10
> * Problem Description: Build Failed Exited with code 6
> 
> [Log.txt](https://github.com/unrealcv/unrealcv/files/7915476/Log.txt) [UBT-UE4Editor-Win64-Development.txt](https://github.com/unrealcv/unrealcv/files/7915477/UBT-UE4Editor-Win64-Development.txt)

Hello, have you solve this problem now?

**Comment by hxu296** [comment]
Hello friend from the internet. For your convenience, I created a PR that does the updates mentioned by @Ericgeese. I updated for error 1 and 2, but not for 3, as I did not encounter it. Here is the PR: #234

**Comment by zfw1226** [comment]
> 

I have merged your suggestion in the latest branch `4.27-stable`, and this branch can be successfully built with the automation tool. Thanks for your contribution!
