### ISSUE TITLE
Problems detecting the position of the cameras, using Unreal engine 4.27

### ISSUE THREAD

**Issue by wilbercl** [unrealcv/unrealcv#225]
- Operating System: Window 11
- UE4 Version: 4.27.2
- UnrealCV Version: 0.4.2
- Client (python2, 3 or matlab): Python 3.9
- Problem Description: 

I need to be able to detect the poses of the cameras (65) that are in an Unreal scene. I found a plugin called UnrealCV but it is for Unreal version 4.16 and when I run my code I get the following error:
`ERROR:__init__:205:Can not connect to ('localhost', 9000) 
ERROR:__init__:206:Error [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
ERROR:__init__:153:Fail to send message, client is not connected`

Then I try to generate the binaries for a different engine, executing the following:

`git clone https://github.com/unrealcv/unrealcv`
`cd unrealcv`
`python build.py --UE4 "C:\Program Files\Epic Games\UE_4.27"`

And I get the following error:
`Running AutomationTool...
Parsing command line: BuildPlugin -plugin=C:\Users\wconcepcion\Desktop\blender-test\unrealcv\UnrealCV.uplugin -package=C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV -rocket -targetplatforms=Win64
Copying 181 file(s) using max 64 thread(s)
Size mismatch C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md = 0 to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md = 1991
Failed to copy C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md, deleting, waiting 10s and retrying.
Size mismatch C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md = 0 to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md = 1991
Failed to copy C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md, deleting, waiting 10s and retrying.
Size mismatch C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md = 0 to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md = 1991
Failed to copy C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md, deleting, waiting 10s and retrying.
Size mismatch C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md = 0 to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md = 1991
Failed to copy C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md, deleting, waiting 10s and retrying.
Size mismatch C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md = 0 to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md = 1991
Failed to copy C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md, deleting, waiting 10s and retrying.
Size mismatch C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md = 0 to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md = 1991
Failed to copy C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md, deleting, waiting 10s and retrying.
Size mismatch C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md = 0 to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md = 1991
Failed to copy C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md, deleting, waiting 10s and retrying.
Size mismatch C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md = 0 to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md = 1991
Failed to copy C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md, deleting, waiting 10s and retrying.
Size mismatch C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md = 0 to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md = 1991
Failed to copy C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md, deleting, waiting 10s and retrying.
Size mismatch C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md = 0 to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md = 1991
ERROR: Failed to copy C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md
ERROR: Failed to copy C:\Users\wconcepcion\Desktop\blender-test\unrealcv\docs\index.md to C:\Users\wconcepcion\Desktop\blender-test\unrealcv\Plugins\UnrealCV\HostProject\Plugins\UnrealCV\docs\index.md
       (see C:\Users\wconcepcion\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.27\Log.txt for full exception trace)
AutomationTool exiting with ExitCode=1 (Error_Unknown)
BUILD FAILED`

Can somebody help me? Thanks!

**Comment by dklee98** [comment]
I have same issue. Did you solve it?

**Comment by dklee98** [comment]
I solve this issue deleting 'docs' directory. However, there are still error..
Did you solve it perfectly? I used UE4 5.0.0

**Comment by zfw1226** [comment]
Hi @wilbercl , you can try the recent `4.27-stable` branch, I think the build problem has been solved.
