### ISSUE TITLE
How to convert the depth into disparity?

### ISSUE THREAD

**Issue by 4bitadder** [unrealcv/unrealcv#229]
Hello

I want to use the unrealcv engine to generate some stereo image for disparity estimation.

What I did is setting two cameras into different location, and grabbing the corresponding RGB and depth images.

But I had some problems when converting the depth into disparity.

Since the unit of extracted depth image is in meter (e.g., 2.5m), but the focal length is in pixel (W/2=320pixels)

The baseline is the distance between two cameras, where the unit is also in pixels (e.g., 50 pixels)

How to compute the disparity using the following equation? If directly copying the above numbers, the disparity will be super large.

depth * disparity = Baseline * focal_length

Thanks a lot

**Comment by 4bitadder** [comment]
> Maybe the [UnrealStereo](https://github.com/edz-o/unreal-stereo-evaluation) project will help you.

Thanks. But it seems that the UnrealStereo dataset provides the disparity ground-truth with corresponding left-right images.

But what we want to do is placing the two cameras in a top-down position, which is different as the UnrealStereo images. (similar to conventional left-right scenario where all objects are rotated 90 degree).

In the UnrealStereo paper, the authors claimed that the disparity is calculated by disparity = baseline * focal_length / depth. So is there any conversion which can normalize the depth (in meter) with focal length and camera baseline (in pixel)?

**Comment by edz-o** [comment]
The baseline should be in the same unit as depth because the camera is in the world coordinate. So disparity should have the same unit as focal length (pixel).

**Comment by 4bitadder** [comment]
> The baseline should be in the same unit as depth because the camera is in the world coordinate. So disparity should have the same unit as focal length (pixel).

For example, if I set the camera 0 location by

vset /camera/0/location 100 100 120

and capture an image

then I move the camera 0 as

vset /camera/0/location 100 100 100

to capture another image

Does it mean that the baseline is 20 (the z coordinate displacement)? And what is the unit of this 20?

I might be wrong since I am new to this domain. Thanks

**Comment by edz-o** [comment]
> > The baseline should be in the same unit as depth because the camera is in the world coordinate. So disparity should have the same unit as focal length (pixel).
> 
> For example, if I set the camera 0 location by
> 
> vset /camera/0/location 100 100 120
> 
> and capture an image
> 
> then I move the camera 0 as
> 
> vset /camera/0/location 100 100 100
> 
> to capture another image
> 
> Does it mean that the baseline is 20 (the z coordinate displacement)? And what is the unit of this 20?
> 
> I might be wrong since I am new to this domain. Thanks

The baseline is 20 if the cameras are [rectified](https://en.wikipedia.org/wiki/Image_rectification). The unit of 20 is the unit in the UE world which can be considered as scaled distance metric.
