### ISSUE TITLE
How to embed a new game?

### ISSUE THREAD

**Issue by jason718** [unrealcv/unrealcv#23]
Hi Weichao,

How to embed my own game with this beautiful unrealcv plugin? I built some maps and want to use this program to get some screenshots for research. How can I do this?

Thanks!

**Comment by mikeroberts3000** [comment]
Also curious about this :)

**Comment by qiuwch** [comment]
Hi, @jason718 @mikeroberts3000:

I am writing a tutorial about this. I will add a new repo called unrealcv/playground, which contains an Unreal Engine project to demonstrate this.

@jason718, sorry for late reply, really busy with other feature requests of unrealcv recently.

**Comment by qiuwch** [comment]
Will include this in http://unrealcv.readthedocs.io/en/latest/ (still under construction).
