### ISSUE TITLE
Can't Build for UE4.27 on Ubuntu

### ISSUE THREAD

**Issue by wukui-muc** [unrealcv/unrealcv#235]
- Operating System: Linxu (ubuntu1804)
- UE4 Version:4.27
- UnrealCV Version:4.27-stable
- Client (python2, 3 or matlab):python3
- Problem Description:
I follow the instruction to build the unrealcv 4.27 , but error occured when building from source 

comman line:
        git checkout 4.27-stable
        pip install -U unrealcv
        python build.py --UE4 "/home/wuk/UnrealEngine-4.27.0-release/"

error message:
/home/wuk/unrealcv/Plugins/UnrealCV/HostProject/Plugins/UnrealCV/Source/UnrealCV/Private/BPFunctionLib/VisionBPLib.cpp:395:21: error: no matching member function for call to 'GetRaw'
                  if (ImageWrapper->GetRaw(ERGBFormat::BGRA, 8, UncompressedBGRA))
                      ~~~~~~~~~~~~~~^~~~~~

**Comment by zfw1226** [comment]
The auto-build script `build.py` is deprecated. 
You are required to compile the Plugin in Visual Studio.
