### ISSUE TITLE
What are the internal parameters of FunsionCamSensor

### ISSUE THREAD

**Issue by KSdong** [unrealcv/unrealcv#236]
What are the internal parameters of FunsionCamSensor？
intrinsic_2d_camera
intrinsic_3d_camera
dist_coefficients
intrinsic
intrinsic_cam2d_in_cam3d

**Comment by zfw1226** [comment]
You can refer to some existing blogs for more details, such as [The intrinsic of UnrealCV camera](https://miaodx.com/blogs/unrealcv_digest/unrealcv_K/), and [Convert Ray-Distance Returned from UnrealCV To Depth Map](https://dev.classmethod.jp/articles/convert-ray-distance-returned-from-unrealcv-to-depth-map-2/).
