### ISSUE TITLE
Unrecognized image file extension for "npy"

### ISSUE THREAD

**Issue by Buffyqsf** [unrealcv/unrealcv#237]
- Operating System: windows 10
- UE4 Version: 4.16.3
- UnrealCV Version: 0.3.10
- Client (python2, 3 or matlab): python 3
- Problem Description:

I try to use unreal cv command to save depth image in fomat npy. But not like lit image in format png, I run console command "vget /camera/0/depth result/cameraPawn.npy" but got nothing in my computer. 
It seems that unrealcv doesn't support saving the npy file directly to computer?

![image](https://github.com/unrealcv/unrealcv/assets/89965829/ce2d40b5-c504-469b-92b3-f3428b97fb4c)

**Comment by zfw1226** [comment]
Hi @Buffyqsf, the `npy` format is supported in the newer version of UnrealCV, e.g. the `4.27-stable` branch.
