### ISSUE TITLE
UE5.2 Missing Headers for unrealcv 5.2 Branch

### ISSUE THREAD

**Issue by KaiMJ** [unrealcv/unrealcv#245]
Compile error due to missing Engine headers. This happened during my Ubuntu 20.04 UE 5.2 compiled from source.

Fix: Add about 7 headers to the specific files. Now build should work.

`
diff --git a/Source/UnrealCV/Private/Actor/DataCaptureActor.cpp b/Source/UnrealCV/Private/Actor/DataCaptureActor.cpp
index 7040430..3e7ce05 100644
--- a/Source/UnrealCV/Private/Actor/DataCaptureActor.cpp
+++ b/Source/UnrealCV/Private/Actor/DataCaptureActor.cpp
@@ -6,7 +6,7 @@
 #include "Runtime/Engine/Classes/Components/MaterialBillboardComponent.h"
 #include "Runtime/CoreUObject/Public/UObject/ConstructorHelpers.h"
 #include "Runtime/Core/Public/GenericPlatform/GenericPlatformFile.h"
-#include "Runtime/Core/Public/HAL/PlatformFilemanager.h"
+#include "Runtime/Core/Public/HAL/PlatformFileManager.h"
 #include "Runtime/Engine/Classes/Animation/SkeletalMeshActor.h"
 #include "Runtime/Engine/Classes/Kismet/GameplayStatics.h"
 #include "Runtime/Engine/Classes/Materials/Material.h"
diff --git a/Source/UnrealCV/Private/BPFunctionLib/VisionBPLib.cpp b/Source/UnrealCV/Private/BPFunctionLib/VisionBPLib.cpp
index 10bbc42..7556df2 100644
--- a/Source/UnrealCV/Private/BPFunctionLib/VisionBPLib.cpp
+++ b/Source/UnrealCV/Private/BPFunctionLib/VisionBPLib.cpp
 #include "FusionCamSensor.h"
 #include "UnrealcvLog.h"
 #include "WorldController.h"
+#include "Engine/Texture2D.h"
+#include "TextureResource.h"
 
 // TODO: Move features outside blueprint function library.
 
diff --git a/Source/UnrealCV/Private/Commands/CameraHandler.cpp b/Source/UnrealCV/Private/Commands/CameraHandler.cpp
index 19fa4e3..f8e5363 100644
--- a/Source/UnrealCV/Private/Commands/CameraHandler.cpp
+++ b/Source/UnrealCV/Private/Commands/CameraHandler.cpp
@@ -17,6 +17,7 @@
 #include "FusionCameraActor.h"
 
 #include "UnrealcvStats.h"
+#include "UnrealClient.h"
 
 DECLARE_CYCLE_STAT(TEXT("FCameraHandler::GetCameraLit"), STAT_GetCameraLit, STATGROUP_UnrealCV);
 DECLARE_CYCLE_STAT(TEXT("FCameraHandler::SaveData"), STAT_SaveData, STATGROUP_UnrealCV);
diff --git a/Source/UnrealCV/Private/Sensor/CameraSensor/DepthCamSensor.cpp b/Source/UnrealCV/Private/Sensor/CameraSensor/DepthCamSensor.cpp
index a9f32b0..e30700b 100644
--- a/Source/UnrealCV/Private/Sensor/CameraSensor/DepthCamSensor.cpp
+++ b/Source/UnrealCV/Private/Sensor/CameraSensor/DepthCamSensor.cpp
@@ -1,6 +1,7 @@
 // Weichao Qiu @ 2017
 #include "DepthCamSensor.h"
 #include "AnnotationCamSensor.h"
+#include "TextureResource.h"
 
 UDepthCamSensor::UDepthCamSensor(const FObjectInitializer& ObjectInitializer) :
        Super(ObjectInitializer)
diff --git a/Source/UnrealCV/Private/Sensor/CameraSensor/LitCamSensor.cpp b/Source/UnrealCV/Private/Sensor/CameraSensor/LitCamSensor.cpp
index c050c4f..ca8a42f 100644
--- a/Source/UnrealCV/Private/Sensor/CameraSensor/LitCamSensor.cpp
+++ b/Source/UnrealCV/Private/Sensor/CameraSensor/LitCamSensor.cpp
@@ -4,7 +4,7 @@
 #include "UnrealcvStats.h"
 
 #include "Runtime/Engine/Classes/Engine/Engine.h"
-
+#include "Engine/TextureRenderTarget.h"
 
 DECLARE_CYCLE_STAT(TEXT("ULitCamSensor::CaptureLit"), STAT_CaptureLit, STATGROUP_UnrealCV);
 
diff --git a/Source/UnrealCV/Private/Server/ServerConfig.cpp b/Source/UnrealCV/Private/Server/ServerConfig.cpp
index d41ee00..64088f3 100644
--- a/Source/UnrealCV/Private/Server/ServerConfig.cpp
+++ b/Source/UnrealCV/Private/Server/ServerConfig.cpp
@@ -3,11 +3,12 @@
 #include "Runtime/Core/Public/HAL/FileManager.h"
 #include "Runtime/Core/Public/Misc/ConfigCacheIni.h"
 #include "Runtime/Core/Public/Misc/CommandLine.h"
-#include "Modules/ModuleManager.h"
-#include "AssetRegistryModule.h"
+#include "Modules/ModuleManager.h"
+#include "AssetRegistryModule.h"
 
 
 #include "UnrealcvLog.h"
+#include "AssetData.h"
 
 // TODO: Try to simplify the implementation of this class
 FServerConfig::FServerConfig()
diff --git a/Source/UnrealCV/Private/UnrealcvGameMode.cpp b/Source/UnrealCV/Private/UnrealcvGameMode.cpp
index 0eedef8..63f5ce6 100644
--- a/Source/UnrealCV/Private/UnrealcvGameMode.cpp
+++ b/Source/UnrealCV/Private/UnrealcvGameMode.cpp
@@ -4,6 +4,7 @@
 #include "ImageUtils.h"
 #include "UnrealcvServer.h"
 #include "UnrealcvLog.h"
+#include "Components/InputComponent.h"
 
 AUnrealcvGameMode::AUnrealcvGameMode()
 {
`

**Comment by zfw1226** [comment]
Thanks for your report. The missing headers have been added in 5.2 branch.
