### ISSUE TITLE
Could not be compiled. Try rebuilding from source manually

### ISSUE THREAD

**Issue by eli-nartey** [unrealcv/unrealcv#249]
- Operating System: Windows 11
- UE4 Version: 4.27
- UnrealCV Version: 4.27
- Client (python2, 3 or matlab): python 3
- Problem Description:
* After moving the unzipped unrealcv files to a new Plugin folder as instructured I get the error below when I try to open my Unreal Engine Project:
" `name of project` could not be compiled. Try rebuilding from source manually.

**Comment by zfw1226** [comment]
Can you see the report logs/errors when rebuilding from source?

**Comment by eli-nartey** [comment]
I get this dialog box first.
![55-unrealcverrors](https://github.com/unrealcv/unrealcv/assets/154381503/d936c2c5-03b4-4d38-ae10-92d37e1d3d4f)

When I choose "Yes", then I get this Window.
![56-unrealcverrors](https://github.com/unrealcv/unrealcv/assets/154381503/e274e9e2-7fc3-41ff-b421-c6293dbd8f01)

After I choose "Okay", it closes and nothing happens after that.

**Comment by zfw1226** [comment]
Are you running a Blueprint project or a C++ project?

**Comment by HapyRain** [comment]
You just need to copy the UnrealCV engine file to another location first, then delete the corresponding plugin. After that, open UE and run the corresponding project. Once it works, turn off UnrealCV in the plugin, restart UE, and then reinstall the plugin.

**Comment by eli-nartey** [comment]
Thanks for the help but unfortunately I am not getting the instructions clearly:

Step 1: Remove the unrealcv engine file from the Plugins location of my project
Step 2: Remove the unrealcv engine file from the Plugins location in the Epic Games Program Files location.

Then what do I next please?

> You just need to copy the UnrealCV engine file to another location first, then delete the corresponding plugin. After that, open UE and run the corresponding project. Once it works, turn off UnrealCV in the plugin, restart UE, and then reinstall the plugin.
