### ISSUE TITLE
Support for Linux Unreal 4.13?

### ISSUE THREAD

**Issue by daeilkim** [unrealcv/unrealcv#29]
Wondering which versions of Unreal this plugin is supported for. Tried to install the plugin via your instructions after the build for Linux and got this error:

/home/daeil/Programs/UnrealEngine4.13/Engine/Plugins/unrealcv/Binaries/Linux/libUE4Editor-UnrealCV.so: symbol _ZN7UObject7PreSaveEv, version UE4 not defined in file libUE4Editor-CoreUObject.so with link time reference
[2016.10.15-19.55.00:799][  0]LogModuleManager:Warning: ModuleManager: Unable to load module '/home/daeil/Programs/UnrealEngine4.13/Engine/Plugins/unrealcv/Binaries/Linux/libUE4Editor-UnrealCV.so' because the file couldn't be loaded by the OS.

Any tips on solving this would be much appreciated. Thanks!

**Comment by qiuwch** [comment]
This plugin is developed and tested in 4.12. We are working on solving the compatible issue with 4.13, which is also reported in #20, I will report my progress to you later. 

Please try `git clone -b 4.12 https://github.com/EpicGames/UnrealEngine.git`.
Epic Games just updated their [instruction page](https://wiki.unrealengine.com/Building_On_Linux) a few days ago from 4.12 to 4.13.

**Comment by qiuwch** [comment]
@daeilkim, I was very busy during the past few weeks. I already updated the code to support 4.13 and 4.14. And will upload the plugin binaries later today. Sorry for this late update.

I will close this issue. If you find this issue still exists, please feel free to reopen it.
