### ISSUE TITLE
How to create a game binary of a virtual world for UnrealCV ?

### ISSUE THREAD

**Issue by sudk1896** [unrealcv/unrealcv#39]
Hey,
I want to create a short game binary, similar to the one provided on the `unrealcv` website. How would I go about it ?
Thanks.

**Comment by qiuwch** [comment]
HI, @sudk1896:

Do you want to know how to package a game, or how to put the game to our website?

I am writing a tutorial for the first one, which will take me a bit more time.
For the second one, you can host your content to anywhere, and put a link to this page by making a pull request.  https://github.com/unrealcv/unrealcv.github.io/blob/master/_pages/model_zoo.md

**Comment by sudk1896** [comment]
@qiuwch : Thanks for the reply. I wanted to know how to package a game. Once I make it, I will surely upload it. Any idea of a tentative time by which you would finish the tutorial ? 
Regards.

**Comment by qiuwch** [comment]
Hi @sudk1896,

I fixed a bug that will prevent packaging a game using the `Package game` option from the UE4Editor menu. If you update to the v0.3.0 release, you can use the `File - Package Project - [Your platform]` to create a binary.

**Comment by doublerebel** [comment]
Packaging is working for me using `Package game`, I think this issue can be closed?
