### ISSUE TITLE
object_mask in standalone mode

### ISSUE THREAD

**Issue by alexhbkim** [unrealcv/unrealcv#48]
Hi,

First of all, thank you very much for the plugin. I'm new to unreal and I'm learning a lot going through the code.

I have a question about object_mask in standalone mode. I downloaded the RealisticRendering example and tried the plugin and it works well. I'm attaching the screen shot of running it against the unreal starter content.
![object_mask_editor](https://cloud.githubusercontent.com/assets/2468901/23043929/fd7fbd18-f452-11e6-9c45-fc2cdd7dfad5.jpg)

However, when I run the vset /viewmode object_mask mode in standalone mode, it changes the lighting but doesn't change colors. It kind of looks like it's running the FViewMode::VertexColor, but not PaintObject routine in FPlayerViewMode::Object
![object_mask_standalone](https://cloud.githubusercontent.com/assets/2468901/23044012/47c6d3b6-f453-11e6-88a4-c75e1392050e.jpg)

I'm attaching the lit mode for comparison
![lit_standalone](https://cloud.githubusercontent.com/assets/2468901/23044027/525f86ec-f453-11e6-9bf1-6c13623dd165.jpg)

Is that anything I need to do during packaging process to make this work? or do you have any suggestion on what might be the problem please?

I would appreciate any insight you might have on this.

thanks, :-)
alex

**Comment by qiuwch** [comment]
http://docs.unrealcv.org/en/latest/plugin/package-game/. Try the step "Modify an UE4 config file" to see whether it can solve your problem.

**Comment by alexhbkim** [comment]
That works great! and thank you very much for your prompt response! :-)

I didn't know about the document link, looks like it has many other useful information there too.

thanks, :-)
alex
