### ISSUE TITLE
vget /camera/[id]/object_mask resets the object mask colors

### ISSUE THREAD

**Issue by ayush-agrawal** [unrealcv/unrealcv#53]
Hey, 

I'm using the plugin v0.3 with UE 4.13. I'm trying to define my own colors for the object mask of different objects in the scene using 'vset /object/[object_name]/color [r] [g] [b]'. However, when I use 'vget /camera/[id]/object_mask', to capture the image, the object mask colors are reset. Is there something wrong I'm doing here?

Thanks, 
Ayush

**Comment by qiuwch** [comment]
This has been fixed in the v0.3.9, please see the last example here. http://docs.unrealcv.org/en/develop/tutorials/generate_images_tutorial.html

**Comment by qiuwch** [comment]
I am closing this. If anyone still finds this issue, please reopen it.
