### ISSUE TITLE
UnrealCV does not build on Mac with Unreal 4.16

### ISSUE THREAD

**Issue by bcbrock** [unrealcv/unrealcv#61]
For the record, I'm going to ask and answer my own question. This is related to #55. 

When trying to execute `build.sh` on my Mac, I received errors very similar to those shown in the 3rd comment in #55. This is what is happening: By default, when you install the Unreal engine on a Mac, it installs the engine in `/Users/Shared/Epic Games/...`. The build issue is caused by the space in the file path, as I learned here: 

https://answers.unrealengine.com/questions/579232/cannot-package-on-macos-no-automationtoolexe.html

To solve the issue, uninstall the engine and reinstall it, but edit the installation file path to remove the space. Instructions for removing the Unreal engine can be found here:

https://answers.unrealengine.com/questions/32845/how-to-uninstall-ue4.html

These instructions are a bit dated - you'll want to remove `/Users/Shared/Epic Games/` instead of `/Users/Shared/UnrealEngine/`, but everything else is the same I believe. 

The master branch plugin appears to work with Unreal 4.16.1, subject to the caveat of issue #46, that is, none of the commands return values when called from a Python client.

**Comment by qiuwch** [comment]
The latest update has fixed #46. The space issue can be fixed by adding a quote to the ${UE4} variable to make it looks like this "${UE4}", this has also been updated to the build.sh. This is simpler than deleting and reinstalling the engine.

**Comment by bcbrock** [comment]
Thank you.

**Comment by mhtong** [comment]
It doesn't appear like the quotes fix it - I was getting errors with the latest version from github until I followed bcbrock's fix.

**Comment by analog-cbarber** [comment]
Yes, this is still broken. Reinstalling with no space in install directory fixes the problem as suggested in the first comment . Should this be reopened?

**Comment by cjauvin** [comment]
This is still an issue as of today, in September 2018.
