### ISSUE TITLE
How to use UnrealCV with UE4 games?

### ISSUE THREAD

**Issue by danielnjoo** [unrealcv/unrealcv#67]
Can you plug UnrealCV into existing UE4 games, or does it only work with games that were packaged with it embedded inside, i.e. the games currently available on Model Zoo?

Thanks! Sorry if this has been answered elsewhere, I did try and look for the answer but wasn't too sure. I've tried it successfully with Realistic Rendering.

**Comment by qiuwch** [comment]
Hi, @danielnjoo 

Currently we are not able to inject UnrealCV into compiled games. It might be possible for a hacker to do so by injecting code into a dll.

You can find UE4 projects in this page http://docs.unrealcv.org/en/master/reference/ue4_resources.html. The RealsiticRendering you tried is from the "Unreal Engine feature examples" of this page.
