### ISSUE TITLE
Is it possible to send action command from the client to UE?

### ISSUE THREAD

**Issue by ahtsan** [unrealcv/unrealcv#70]
It would be useful for reinforcement training in UE. Thanks.

**Comment by qiuwch** [comment]
Yes, we have a demo to call Blueprint function through UnrealCV, which enables doing this. Will release it soon.

**Comment by qiuwch** [comment]
If the action is keyboard action or mouse action, you can already do it with the command. vset /action/keyboard [key_name] [delta]

See http://docs.unrealcv.org/en/master/CHANGELOG.html

**Comment by ahtsan** [comment]
Is there a guide to build unrealcv for the latest version? The simply shell script is still in old version. Thanks.

**Comment by ahtsan** [comment]
With some reasons the build.bat doesn't work. I managed to solve the problem and now built version 0.3.9. Thanks.
