### ISSUE TITLE
Under depth mode, other characters cannot be seen?

### ISSUE THREAD

**Issue by ahtsan** [unrealcv/unrealcv#71]
Is it enabled? I believe this is needed for many purposes. Thanks.

**Comment by ahtsan** [comment]
like other AI

**Comment by qiuwch** [comment]
What is the UnrealCV version and what is the class type of other AI?

**Comment by ahtsan** [comment]
version: 4.12
class type: inherited from Character

**Comment by ahtsan** [comment]
After building 0.3.9, it works. Thanks.
