### ISSUE TITLE
Cannot open console using Brazilian keyboard

### ISSUE THREAD

**Issue by perone** [unrealcv/unrealcv#8]
Cannot open the console on the RealisticRendering example using Brazilian keyboard:

https://en.wikipedia.org/wiki/Portuguese_keyboard_layout

**Comment by qiuwch** [comment]
Sorry, I have no idea, did you try this key (the center key in the screenshot) while holding shift?

![key](https://cloud.githubusercontent.com/assets/1688418/18534696/fb1319be-7abb-11e6-8634-2c0f3c07f7c8.PNG)

[Unreal Engine AnswerHub](https://answers.unrealengine.com/) might be a better place to find the answer .

It is also possible to find the answer by digging inside the Unreal Engine source code, but it is quite time-consuming.

**Comment by fredericp** [comment]
Add this to `RealisticRendering/Saved/Config/Input.ini`

``` 
[/Script/Engine.InputSettings]
ConsoleKeys=F10
```

Now you can open the console with F10

**Comment by perone** [comment]
Thanks @qiuwch and @fredericp, I added the config into `input.ini` and it worked fine.
