### ISSUE TITLE
Is there anyone able to get image using python 3?

### ISSUE THREAD

**Issue by ahtsan** [unrealcv/unrealcv#92]
Normal string works for me but got decoding issue for images.

**Comment by zfw1226** [comment]
Have you tried the newest version(v3.10)? it should work well to get images using python3.

**Comment by qiuwch** [comment]
Hi, @ahtsan: I agree with @zfw1226 . What you need to do is `pip install -U unrealcv`, which will upgrade the python client to the newest version.
