### ISSUE TITLE
[Model ZOO] Newer versions wanted!

### ISSUE THREAD

**Issue by MiaoDX** [unrealcv/unrealcv#93]
Hei,

Thanks for this projects, it helps **A LOT** in my projects!

I am wondering, the projects evolves pretty fast and have somewhat breaking changes. As for the [model zoo](http://docs.unrealcv.org/en/master/reference/model_zoo.html), it seems only `RealisticRendering` is up-to-date, a.k.a the 0.3.9 version. So, will you update other binaries? 

To me, one more outdoor scene is enough, like the `UrbanCity` one.  To make newer versions of unrealcv integrated with it, maybe we can do with the help of the [doc on packing](http://docs.unrealcv.org/en/master/plugin/package.html) and [qiuwch/unrealcv-packaging](https://github.com/qiuwch/unrealcv-packaging). However, the scenario is [costing $84.99](https://www.unrealengine.com/marketplace/urban-city), which is somewhat out of my budget.

That said, are we safe to use the re-distributed binaries in academic or commercial field?

Looking for your reply!

**Comment by qiuwch** [comment]
I am working on this, rewriting some packaging scripts to automate this procedure.

**Comment by MiaoDX** [comment]
Ok, then I will close it now, thanks a lot. :)
