### ISSUE TITLE
cannot connect localhost 9000

### ISSUE THREAD

**Issue by TianyuanYu** [unrealcv/unrealcv#94]
Hi,

I use Ubuntu, after 'pip install unrealcv', I tried 

"from unrealcv import client
client.connect()". 

But it shows 

''ERROR:__init__:168:Can not connect to ('localhost', 9000)
ERROR:__init__:169:Error [Errno 111] Connection refused"

What should I do to connect?

Thanks in advance

**Comment by qiuwch** [comment]
Is the binary running? If you use `vget /unrealcv/status` in the console. What do you see?

**Comment by qiuwch** [comment]
I am closing it right now. Please reopen if this is not resolved.

**Comment by Instantnoodles-madman** [comment]
> Is the binary running? If you use `vget /unrealcv/status` in the console. What do you see?

i have the same question
it reported scheme missing when I acted the command wget /unrealcv/status

**Comment by Instantnoodles-madman** [comment]
> @qiuwch , hello, my unrealcv suddenly can't connect to the environment from yesterday. like this:
> 
> > > > from  unrealcv import client
> > > > client.connect()
> > > > ERROR:**init**:205:Can not connect to ('localhost', 9000)
> > > > ERROR:**init**:206:Error [Errno 111] Connection refused
> > > > False
> 
> I don't know the reason, can you help me to solve this problem?

have you solved this problem?

**Comment by xi-mao** [comment]
@Instantnoodles-madman   Please refer to #193
